#version: "3.8"

services:
  frontend:
    build: ./tienda-tech-frontend
    container_name: tienda-tech-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  backend:
    build: ./tienda-tech-backend
    container_name: tienda-tech-backend
    environment:
      DB_HOST: db
      DB_USER: alumno
      DB_PASSWORD: alumno123
      DB_NAME: tienda_tecnologica
      DB_PORT: 3306
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  db:
    build: ./tienda-tech-db
    container_name: tienda-tech-db
    ports:
      - "3306:3306"
    volume