version: 2

updates:
  # Dependencias de Node.js (backend)
  - package-ecosystem: "npm"
    directory: "/tienda-tech-backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependabot"
      - "seguridad"

  # Dependencias de GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependabot"
      - "github-actions"